import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminSidebar from "@/Components/admins/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col md:flex-row min-h-screen bg-black w-full overflow-x-hidden">
<AdminSidebar />
<div className="flex-1 w-full">
        {children}
</div>
      </body>
    </html>
  );
}
